### ISSUE TITLE
version 1.6.4 not showed correctly

### ISSUE THREAD

**Issue by trentasis** [jackburton79/ocs-agent#32]
It seems that was not released with version numberhttps://github.com/jackburton79/ocs-agent/commit/5b5d887b3bd5619181006d924c2f1274f2cf79bf

Release 1.6.5 or 1.7?

**Comment by jackburton79** [comment]
Hi,
1.7 is a pre-release which contains many changes not yet stabilized, which I wouldn't recommend for production yet.
Latest released version is 1.6.4, here: https://github.com/jackburton79/ocs-agent/releases/tag/v1.6.4, which contains most fixes included in 1.7, but not the new features.

**Comment by trentasis** [comment]
Ok, I think that 1.6.4 show as version number 1.6.3

**Comment by jackburton79** [comment]
I just did a fresh checkout of the v1.6.4 tag and it correctly shows 1.6.4 as version, both in the help text and in the output of the --version command.
