### ISSUE TITLE
Fail to compile 

### ISSUE THREAD

**Issue by inext68** [jackburton79/ocs-agent#45]
Hello, 
I found your project and this is very useful for my work to inventory 10zig Thinclients into GLPI (or Ocsinventory).
I tryed to complile on linux Ubuntu 22.04.4.LTS but I receive the error below.
Hope you can solve . 
Thanks for you work.

-----------------------------------------------------------------------------------
----/ocs-agent-2.0.0$
<<>>...<<>>

Building file: http/SocketGetter.cpp
Invoking: GCC C++ Compiler
g++ -DTIXML_USE_STL -fPIE -O2 -Wall -I ./ -c -fmessage-length=0 -MMD -MP -MF"http/SocketGetter.d" -MT"http/SocketGetter.d" -o "http/SocketGetter.o" "http/SocketGetter.cpp"
In file included from http/SocketGetter.cpp:11:
http/SSLSocket.h:13:10: fatal error: openssl/ssl.h: No such file or directory
   13 | #include <openssl/ssl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [subdir.mk:41: http/SocketGetter.o] Error 1

**Comment by jackburton79** [comment]
Hi, try installing openssl_devel as a dependency

**Comment by inext68** [comment]
Thank you. 
Now I can complile it.

**Comment by jackburton79** [comment]
Nice!
